# yaml-language-server: $schema=./node_modules/wrangler/config-schema.json
name = "unidrop"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"
