/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyCollegeRouteImport } from './routes/verify-college'
import { Route as TrackRouteImport } from './routes/track'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MerchantTrackingRouteImport } from './routes/merchant-tracking'
import { Route as MerchantProfileRouteImport } from './routes/merchant-profile'
import { Route as MerchantProductsRouteImport } from './routes/merchant-products'
import { Route as MerchantOrdersRouteImport } from './routes/merchant-orders'
import { Route as MerchantCouriersRouteImport } from './routes/merchant-couriers'
import { Route as MerchantAnalyticsRouteImport } from './routes/merchant-analytics'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LendTrackRouteImport } from './routes/lend-track'
import { Route as LendRouteImport } from './routes/lend'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as LendItemIdRouteImport } from './routes/lend-item.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const VerifyCollegeRoute = VerifyCollegeRouteImport.update({
  id: '/verify-college',
  path: '/verify-college',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantTrackingRoute = MerchantTrackingRouteImport.update({
  id: '/merchant-tracking',
  path: '/merchant-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProfileRoute = MerchantProfileRouteImport.update({
  id: '/merchant-profile',
  path: '/merchant-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProductsRoute = MerchantProductsRouteImport.update({
  id: '/merchant-products',
  path: '/merchant-products',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/merchant-orders',
  path: '/merchant-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantCouriersRoute = MerchantCouriersRouteImport.update({
  id: '/merchant-couriers',
  path: '/merchant-couriers',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantAnalyticsRoute = MerchantAnalyticsRouteImport.update({
  id: '/merchant-analytics',
  path: '/merchant-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LendTrackRoute = LendTrackRouteImport.update({
  id: '/lend-track',
  path: '/lend-track',
  getParentRoute: () => rootRouteImport,
} as any)
const LendRoute = LendRouteImport.update({
  id: '/lend',
  path: '/lend',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LendItemIdRoute = LendItemIdRouteImport.update({
  id: '/lend-item/$id',
  path: '/lend-item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lend': typeof LendRoute
  '/lend-track': typeof LendTrackRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/merchant-analytics': typeof MerchantAnalyticsRoute
  '/merchant-couriers': typeof MerchantCouriersRoute
  '/merchant-orders': typeof MerchantOrdersRoute
  '/merchant-products': typeof MerchantProductsRoute
  '/merchant-profile': typeof MerchantProfileRoute
  '/merchant-tracking': typeof MerchantTrackingRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/select-role': typeof SelectRoleRoute
  '/splash': typeof SplashRoute
  '/store': typeof StoreRoute
  '/track': typeof TrackRoute
  '/verify-college': typeof VerifyCollegeRoute
  '/chat/$id': typeof ChatIdRoute
  '/lend-item/$id': typeof LendItemIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lend': typeof LendRoute
  '/lend-track': typeof LendTrackRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/merchant-analytics': typeof MerchantAnalyticsRoute
  '/merchant-couriers': typeof MerchantCouriersRoute
  '/merchant-orders': typeof MerchantOrdersRoute
  '/merchant-products': typeof MerchantProductsRoute
  '/merchant-profile': typeof MerchantProfileRoute
  '/merchant-tracking': typeof MerchantTrackingRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/select-role': typeof SelectRoleRoute
  '/splash': typeof SplashRoute
  '/store': typeof StoreRoute
  '/track': typeof TrackRoute
  '/verify-college': typeof VerifyCollegeRoute
  '/chat/$id': typeof ChatIdRoute
  '/lend-item/$id': typeof LendItemIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lend': typeof LendRoute
  '/lend-track': typeof LendTrackRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/merchant-analytics': typeof MerchantAnalyticsRoute
  '/merchant-couriers': typeof MerchantCouriersRoute
  '/merchant-orders': typeof MerchantOrdersRoute
  '/merchant-products': typeof MerchantProductsRoute
  '/merchant-profile': typeof MerchantProfileRoute
  '/merchant-tracking': typeof MerchantTrackingRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/select-role': typeof SelectRoleRoute
  '/splash': typeof SplashRoute
  '/store': typeof StoreRoute
  '/track': typeof TrackRoute
  '/verify-college': typeof VerifyCollegeRoute
  '/chat/$id': typeof ChatIdRoute
  '/lend-item/$id': typeof LendItemIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/dashboard'
    | '/leaderboard'
    | '/lend'
    | '/lend-track'
    | '/login'
    | '/merchant'
    | '/merchant-analytics'
    | '/merchant-couriers'
    | '/merchant-orders'
    | '/merchant-products'
    | '/merchant-profile'
    | '/merchant-tracking'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/select-role'
    | '/splash'
    | '/store'
    | '/track'
    | '/verify-college'
    | '/chat/$id'
    | '/lend-item/$id'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/dashboard'
    | '/leaderboard'
    | '/lend'
    | '/lend-track'
    | '/login'
    | '/merchant'
    | '/merchant-analytics'
    | '/merchant-couriers'
    | '/merchant-orders'
    | '/merchant-products'
    | '/merchant-profile'
    | '/merchant-tracking'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/select-role'
    | '/splash'
    | '/store'
    | '/track'
    | '/verify-college'
    | '/chat/$id'
    | '/lend-item/$id'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/dashboard'
    | '/leaderboard'
    | '/lend'
    | '/lend-track'
    | '/login'
    | '/merchant'
    | '/merchant-analytics'
    | '/merchant-couriers'
    | '/merchant-orders'
    | '/merchant-products'
    | '/merchant-profile'
    | '/merchant-tracking'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/select-role'
    | '/splash'
    | '/store'
    | '/track'
    | '/verify-college'
    | '/chat/$id'
    | '/lend-item/$id'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LendRoute: typeof LendRoute
  LendTrackRoute: typeof LendTrackRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRoute
  MerchantAnalyticsRoute: typeof MerchantAnalyticsRoute
  MerchantCouriersRoute: typeof MerchantCouriersRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantProductsRoute: typeof MerchantProductsRoute
  MerchantProfileRoute: typeof MerchantProfileRoute
  MerchantTrackingRoute: typeof MerchantTrackingRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  SelectRoleRoute: typeof SelectRoleRoute
  SplashRoute: typeof SplashRoute
  StoreRoute: typeof StoreRoute
  TrackRoute: typeof TrackRoute
  VerifyCollegeRoute: typeof VerifyCollegeRoute
  ChatIdRoute: typeof ChatIdRoute
  LendItemIdRoute: typeof LendItemIdRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-college': {
      id: '/verify-college'
      path: '/verify-college'
      fullPath: '/verify-college'
      preLoaderRoute: typeof VerifyCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-tracking': {
      id: '/merchant-tracking'
      path: '/merchant-tracking'
      fullPath: '/merchant-tracking'
      preLoaderRoute: typeof MerchantTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-profile': {
      id: '/merchant-profile'
      path: '/merchant-profile'
      fullPath: '/merchant-profile'
      preLoaderRoute: typeof MerchantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-products': {
      id: '/merchant-products'
      path: '/merchant-products'
      fullPath: '/merchant-products'
      preLoaderRoute: typeof MerchantProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-orders': {
      id: '/merchant-orders'
      path: '/merchant-orders'
      fullPath: '/merchant-orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-couriers': {
      id: '/merchant-couriers'
      path: '/merchant-couriers'
      fullPath: '/merchant-couriers'
      preLoaderRoute: typeof MerchantCouriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-analytics': {
      id: '/merchant-analytics'
      path: '/merchant-analytics'
      fullPath: '/merchant-analytics'
      preLoaderRoute: typeof MerchantAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lend-track': {
      id: '/lend-track'
      path: '/lend-track'
      fullPath: '/lend-track'
      preLoaderRoute: typeof LendTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lend': {
      id: '/lend'
      path: '/lend'
      fullPath: '/lend'
      preLoaderRoute: typeof LendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lend-item/$id': {
      id: '/lend-item/$id'
      path: '/lend-item/$id'
      fullPath: '/lend-item/$id'
      preLoaderRoute: typeof LendItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LendRoute: LendRoute,
  LendTrackRoute: LendTrackRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRoute,
  MerchantAnalyticsRoute: MerchantAnalyticsRoute,
  MerchantCouriersRoute: MerchantCouriersRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantProductsRoute: MerchantProductsRoute,
  MerchantProfileRoute: MerchantProfileRoute,
  MerchantTrackingRoute: MerchantTrackingRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  SelectRoleRoute: SelectRoleRoute,
  SplashRoute: SplashRoute,
  StoreRoute: StoreRoute,
  TrackRoute: TrackRoute,
  VerifyCollegeRoute: VerifyCollegeRoute,
  ChatIdRoute: ChatIdRoute,
  LendItemIdRoute: LendItemIdRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
